{
	"version": 1553197016,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/bg-sheet1.png",
		"images/bg-sheet2.png",
		"images/bg-sheet3.png",
		"images/bg-sheet4.png",
		"images/bg-sheet5.png",
		"images/correc-sheet0.png",
		"images/gg-sheet0.png",
		"images/hud-sheet0.png",
		"images/btnext-sheet0.png",
		"images/live-sheet0.png",
		"images/heart-sheet0.png",
		"images/gameover-sheet0.png",
		"images/btrestert-sheet0.png",
		"images/cover-sheet0.png",
		"images/spritefont.png",
		"images/sprite-sheet0.png",
		"images/hud1-sheet0.png",
		"images/hud2-sheet0.png",
		"images/howtoplay-sheet0.png",
		"images/howto-sheet0.png",
		"images/playgame-sheet0.png",
		"images/particles.png",
		"media/421002__eponn__correct.m4a",
		"media/421002__eponn__correct.ogg",
		"media/363920__samsterbirdies__8-bit-error.m4a",
		"media/363920__samsterbirdies__8-bit-error.ogg",
		"media/264295__foolboymedia__sky-loop (1).m4a",
		"media/264295__foolboymedia__sky-loop (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}